baseURL = "https://larryjameshenry.com/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Larry James Henry"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "larryjameshenry"
googleAnalytics = "G-PW6KZTRCEL"
enableRobotsTXT = true
enableGitInfo = true
summaryLength  = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "January 02 2006"
comments = false
readingTime = false
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"
showPostImage = true

[Params.Author]
  name = "Larry Henry"
  website = "https://www.larryjameshenry.com/"
  authorInfo = "The author info and bio."
  authorPostImage = "/img/author-post-img.jpg"
  email = "sample@gmail.com"
  facebook = "larryjameshenry"
# instagram = "username"
  youtube = "user/larryjameshenry" # or channel/channelname
#  twitter = "username"
  linkedin = "larryjameshenry"
  github = "larryjameshenry"
#  threads = "username"
#  gitlab = "username"
#  reddit = "username"
  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  spotify = "username"
#  paypal = "username"
#  telegram = "username"
#  mastodon = "url"
#  slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

